// Zone configuration for all 10 zones
// Audio files mapped to actual filenames in /public/audio/

export const ZONE_MAX_DURATION = 40; // seconds
export const ZONE_FADE_START = 37; // start fading song
export const ZONE_TRANSITION_TIME = 1; // seconds between zones

export const zones = [
  {
    id: 1,
    name: 'Pop Party',
    nameHe: 'מסיבת פופ',
    emoji: '🎤🎀',
    audioFile: '/audio/קוראים לו שטוקה טוקה פופ.mp3',
    speed: 5,
    obstacleInterval: 2.5,
    isSafeZone: false,
    colors: {
      skyTop: '#FF1493',
      skyBottom: '#00BFFF',
      ground: '#FFB6C1',
      groundAccent: '#FFFFFF',
    },
    obstacles: [
      { type: 'microphone', label: 'Microphone Stand', height: 'ground' },
      { type: 'lollipop', label: 'Giant Lollipop', height: 'ground' },
      { type: 'star', label: 'Spinning Star', height: 'ground' },
      { type: 'fanPoster', label: 'Fan Poster', height: 'ground' },
      { type: 'heartBalloon', label: 'Heart Balloon', height: 'medium', collectible: true, givesLife: true, points: 20 },
    ],
    backgroundElements: ['discoBall', 'spotlights', 'bubbles', 'crowd'],
  },
  {
    id: 2,
    name: 'Cartoon Theme',
    nameHe: 'עולם הקריקטורות',
    emoji: '📺',
    audioFile: '/audio/שטוקה טוקה - קצבי, חצוצרות.mp3',
    speed: 4.5,
    obstacleInterval: 2.75,
    isSafeZone: false,
    colors: {
      skyTop: '#87CEEB',
      skyBottom: '#B0E0E6',
      ground: '#90EE90',
      groundAccent: '#228B22',
    },
    obstacles: [
      { type: 'bone', label: 'Cartoon Bone', height: 'ground' },
      { type: 'ball', label: 'Dog Toy Ball', height: 'ground' },
      { type: 'acmeBox', label: 'ACME Box', height: 'ground' },
      { type: 'trumpet', label: 'Golden Trumpet', height: 'ground' },
      { type: 'musicNote', label: 'Music Note', height: 'medium' },
    ],
    backgroundElements: ['clouds', 'sun', 'stars'],
  },
  {
    id: 3,
    name: 'Israeli Rock',
    nameHe: 'רוק ישראלי',
    emoji: '🎸🇮🇱',
    audioFile: '/audio/בבוקר הוא קופץ עליי - רוק מזרחי ישראלי.mp3',
    speed: 5,
    obstacleInterval: 2.5,
    isSafeZone: false,
    colors: {
      skyTop: '#2C3E50',
      skyBottom: '#D4AF7A',
      ground: '#8B7355',
      groundAccent: '#6B5B3E',
    },
    obstacles: [
      { type: 'darbuka', label: 'Darbuka', height: 'ground' },
      { type: 'tambourine', label: 'Tambourine', height: 'ground' },
      { type: 'stringLights', label: 'String Lights', height: 'medium' },
      { type: 'zaatar', label: "Za'atar Container", height: 'ground' },
      { type: 'hookah', label: 'Hookah', height: 'ground' },
    ],
    backgroundElements: ['stringLights', 'tiles', 'heatWave'],
  },
  {
    id: 4,
    name: 'Heavy Rock',
    nameHe: 'רוק כבד',
    emoji: '🎸⚡',
    audioFile: '/audio/קוראים לו שטוקה טוקה - רוק כבד.mp3',
    speed: 6,
    obstacleInterval: 2,
    isSafeZone: false,
    colors: {
      skyTop: '#0a0a0a',
      skyBottom: '#1a1a1a',
      ground: '#000000',
      groundAccent: '#9B59B6',
    },
    obstacles: [
      { type: 'electricGuitar', label: 'Electric Guitar', height: 'ground' },
      { type: 'amplifier', label: 'Amplifier', height: 'ground' },
      { type: 'drumSet', label: 'Drum Set', height: 'ground' },
      { type: 'micStand', label: 'Microphone Stand', height: 'ground' },
      { type: 'pyroBurst', label: 'Pyro Burst', height: 'ground' },
    ],
    backgroundElements: ['lightning', 'smoke', 'strobe', 'headbangers'],
  },
  {
    id: 5,
    name: 'Hawaiian Paradise',
    nameHe: 'גן עדן הוואי',
    emoji: '🌺',
    audioFile: '/audio/שטוקה טוקה - הוואי מלא.mp3',
    speed: 4,
    obstacleInterval: 3,
    isSafeZone: false,
    colors: {
      skyTop: '#FF6347',
      skyBottom: '#40E0D0',
      ground: '#F4A460',
      groundAccent: '#DEB887',
    },
    obstacles: [
      { type: 'pineapple', label: 'Pineapple', height: 'ground' },
      { type: 'lei', label: 'Lei Garland', height: 'medium' },
      { type: 'surfboard', label: 'Surfboard', height: 'ground' },
      { type: 'coconut', label: 'Coconut', height: 'ground' },
      { type: 'tikiTorch', label: 'Tiki Torch', height: 'ground' },
    ],
    backgroundElements: ['waves', 'palmTrees', 'seagulls', 'sun'],
  },
  {
    id: 6,
    name: 'Reggae Chill',
    nameHe: 'רגאיי',
    emoji: '🎵',
    audioFile: '/audio/שטוקה טוקה- ראגיי.mp3',
    speed: 3.5,
    obstacleInterval: 3.25,
    isSafeZone: false,
    colors: {
      skyTop: '#800080',
      skyBottom: '#FF8C00',
      ground: '#F4A460',
      groundAccent: '#008000',
    },
    obstacles: [
      { type: 'bongoDrums', label: 'Bongo Drums', height: 'ground' },
      { type: 'peaceSign', label: 'Peace Sign', height: 'ground' },
      { type: 'beachChair', label: 'Beach Chair', height: 'ground' },
      { type: 'tropicalDrink', label: 'Tropical Drink', height: 'ground' },
      { type: 'rastaHat', label: 'Rasta Hat', height: 'medium' },
    ],
    backgroundElements: ['palmTrees', 'waves', 'peaceSigns', 'sunset'],
  },
  {
    id: 7,
    name: 'Hawaiian Acoustic',
    nameHe: 'הוואי אקוסטי',
    emoji: '🎸',
    audioFile: '/audio/שטוקה טוקה.- הוואי.mp3',
    speed: 3,
    obstacleInterval: 3.5,
    isSafeZone: false,
    colors: {
      skyTop: '#FF4500',
      skyBottom: '#9370DB',
      ground: '#1a1a1a',
      groundAccent: '#2d2d2d',
    },
    obstacles: [
      { type: 'ukulele', label: 'Ukulele', height: 'ground' },
      { type: 'seashell', label: 'Seashell', height: 'ground' },
      { type: 'flipFlops', label: 'Flip-flops', height: 'ground' },
      { type: 'beachTorch', label: 'Beach Torch', height: 'ground' },
      { type: 'starfish', label: 'Starfish', height: 'ground' },
    ],
    backgroundElements: ['waves', 'fireflies', 'sunset'],
  },
  {
    id: 8,
    name: 'Eastern Vibes',
    nameHe: 'מזרחי',
    emoji: '🪘',
    audioFile: '/audio/בבוקר הוא קופץ עליי - רוסי מזרחי.mp3',
    speed: 4,
    obstacleInterval: 3,
    isSafeZone: false,
    colors: {
      skyTop: '#4B0082',
      skyBottom: '#2C1654',
      ground: '#4169E1',
      groundAccent: '#FFD700',
    },
    obstacles: [
      { type: 'nargila', label: 'Nargila', height: 'ground' },
      { type: 'teaGlass', label: 'Tea Glass', height: 'ground' },
      { type: 'moroccanLamp', label: 'Moroccan Lamp', height: 'medium' },
      { type: 'cushion', label: 'Floor Cushion', height: 'ground' },
      { type: 'plate', label: 'Ornate Plate', height: 'ground' },
    ],
    backgroundElements: ['lanterns', 'fabrics', 'shimmer', 'smoke'],
  },
  {
    id: 9,
    name: 'Grand Finale',
    nameHe: 'הגמר הגדול',
    emoji: '🎺❤️',
    audioFile: '/audio/קוראים לו שטוקה טוקה חצוצרות.mp3',
    speed: 4,
    obstacleInterval: 2,
    isSafeZone: true,
    colors: {
      skyTop: '#FFFFFF',
      skyBottom: '#FFD700',
      ground: '#FFD700',
      groundAccent: '#FFF8DC',
    },
    obstacles: [
      { type: 'goldenHeart', label: 'Golden Heart', height: 'any', points: 100, givesLife: true },
      { type: 'bouquet', label: 'Flowers', height: 'ground', points: 50 },
      { type: 'goldenStar', label: 'Golden Star', height: 'any', points: 50 },
      { type: 'loveLetter', label: 'Love Letter', height: 'medium', points: 75 },
      { type: 'trophy', label: 'Trophy', height: 'ground', points: 100 },
    ],
    backgroundElements: ['confetti', 'fireworks', 'rainbows', 'hearts'],
  },
  {
    id: 10,
    name: 'Ending Song',
    nameHe: 'שיר סיום',
    emoji: '💕',
    audioFile: '/audio/קוראים לו שטוקה טוקה - שיר סיום.mp3',
    speed: 3,
    obstacleInterval: 2.5,
    isSafeZone: true,
    colors: {
      skyTop: '#FFB6C1',
      skyBottom: '#E6E6FA',
      ground: '#FFFFFF',
      groundAccent: '#FFD1DC',
    },
    obstacles: [
      { type: 'floatingHeart', label: 'Heart', height: 'any', points: 50, givesLife: true },
      { type: 'rose', label: 'Rose', height: 'ground', points: 30 },
      { type: 'loveNote', label: 'Love Note', height: 'any', points: 40 },
      { type: 'giftBox', label: 'Gift Box', height: 'ground', points: 60 },
      { type: 'cupidArrow', label: 'Cupid Arrow', height: 'medium', points: 35 },
    ],
    backgroundElements: ['hearts', 'sparkles', 'glow'],
  },
];
